In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("/content/Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [6]:
df.shape

(150, 6)

In [7]:
X=df.drop(columns='Species')
Y=df['Species']
print("Shape of X", X.shape)
print("Shape of Y", Y.shape)

Shape of X (150, 5)
Shape of Y (150,)


In [11]:
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
y=encode.fit_transform(Y)
y2=pd.get_dummies(y).values

In [12]:
y2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [13]:
#spliting data intro train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y2, test_size=0.2, random_state=0)

In [14]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model=Sequential()
model.add(Dense(5,input_shape=(5,),activation='relu'))
model.add(Dense(3,activation='softmax'))

In [22]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [23]:
model.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 1s 3ms/step - loss: 28.7095 - accuracy: 0.3750
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 27.2716 - accuracy: 0.3833
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 26.0172 - accuracy: 0.3833
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 24.5659 - accuracy: 0.3917
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 23.1933 - accuracy: 0.3917
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 21.8557 - accuracy: 0.4000
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 20.4694 - accuracy: 0.4167
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 19.0684 - accuracy: 0.4167
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 17.6484 - accuracy: 0.4250
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 16.2900 - accuracy: 0.4333

In [25]:
pred=model.predict(x_test)
y_test_class=np.argmax(y_test, axis=1)
pred_class=np.argmax(pred, axis=1)

1/1 [==============================] - 0s 23ms/step


In [26]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test_class,pred_class))
print(confusion_matrix(y_test_class,pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.77      0.87        13
           2       0.67      1.00      0.80         6

    accuracy                           0.90        30
   macro avg       0.89      0.92      0.89        30
weighted avg       0.93      0.90      0.90        30

[[11  0  0]
 [ 0 10  3]
 [ 0  0  6]]


In [27]:
(11+10+6)/30

0.9